application:
  title: Vanilla project
  version: 1.0.0

app:
  message: "Copyright by Yassine Fourati 2025 ${spring.application.name}"

spring:
  profiles:
    active: dev
  application:
    name: Vanilla project
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    operationsSorter: method
    default-models-expand-depth: 0
    tagsSorter: alpha
    doc-expansion: none
    operations-sorter: method
  packages-to-scan: com.fourati.vanilla
  model-and-view-allowed: true
